### ISSUE TITLE
Issue when interupting commacd

### ISSUE THREAD

**Issue by Naereen** [shyiko/commacd#12]
Hi,
When launching a commacd command without enough information, a prompt arrives to ask confirmation for which path to chose. That's awesome and I love it.
However, it probably has a bug regarding readline, because if that prompt is interupted (Ctrl+C), then when returning to the sh/bash session, the prompts are non responsive anymore (readline is dead).

- [ ] Can you try to reproduce this bug? (if not, I can include here a screencast showing exactly what happened)
- [ ] Any idea how to fix that?

**Comment by shyiko** [comment]
Hi @Naereen,

You might be hitting a bug described in https://stackoverflow.com/a/38247537/482225. Is it possible for you to upgrade bash? If not, can you please specify your OS & `bash --version && echo $TERM`?

**Comment by Naereen** [comment]
Hi. I am using XUbuntu 17.04 (latest), with GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu), and TERM=screen-256color (but the TERM might be overwritten by my own bashrc I'm not sure).

**Comment by shyiko** [comment]
@Naereen Fixed in [0.3.3](https://github.com/shyiko/commacd/blob/master/CHANGELOG.md#033---2017-10-07) :tada: 

(let me know if you have any issues with it. I compiled `4.3.42(1)` but it's extremely hard to reproduce on my machine (and isn't reproducible at all on bash 4.4+))

**Comment by Naereen** [comment]
Hi,
I tested the latest release, and indeed the issue I talked about is fixed, but now if I Ctrl+C interrupt the prompt, my whole bash session gets killed...
Any idea?

**Comment by shyiko** [comment]
@Naereen Sorry to hear that. Can you please copy&paste output of `stty -a && trap` (before and after commacd ^C)?

**Comment by Naereen** [comment]
No problem, I am glad to try to help fixing it.

Before:
```
speed 38400 baud; rows 42; columns 147; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
trap -- '_exit' EXIT
```

And after (in a superior bash session):
```
speed 38400 baud; rows 42; columns 147; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
trap -- '_exit' EXIT
```
Don't see any difference...

**Comment by shyiko** [comment]
Hm. According to the output you have provided this shouldn't be happening (unless I'm missing something) (my guess at this point is that whatever GUI you have running bash is intercepting the interrupt and acting on it). If you comment out `~/.commacd.bash` in your `~/.bashrc` does the problem still occur?

**Comment by Naereen** [comment]
No, if I don't use `commacd`, of course there is no problem when interrupting it (or maybe I misunderstood your question).

You know, the issue is not too serious, if I am the only one to have encounter this bug, don't work too hard to try to fix it. (I realized that even after a few weeks of installing commacd I did not use it as much as I hoped, I guess after 5+ years of `cd ...<tab>...<tab>` to change directory, it's hard to change your reflex to `, ...<tab>`.)
